# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='pro_startTime',
            field=models.PositiveSmallIntegerField(default=180),
        ),
    ]
